# Site settings
title: Aline Marques
email: alinemarques.dev@gmail.com
description: >-
  Anotações de estudo e desenvolvimento
baseurl: ""
url: "https://alinemarques.dev"
lang: pt_BR
encoding: utf-8
timezone: America/Sao_Paulo
logo: '/assets/images/logo.svg'
# Social links
instagram_username: maarques_aline
github_username: marquesaline
linkedin_username: marques-aline

# Build settings
markdown: kramdown
  
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: '/:name/'

author: Aline Marques

social:
  name: Aline Marques
  links: 
    - https://www.linkedin.com/in/marques-aline/
    - https://github.com/marquesaline

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - Dockerfile
  - docker-compose.yml
  - entrypoint.sh
  - README.md